#!/usr/bin/python

import os
import sys

SCONS_VERSION=os.environ.get('SCONS_VERSION', "2.1.0")

scons_dir = os.path.join(os.path.dirname(__file__), 'scons-' + SCONS_VERSION)

os.execv(os.path.join(scons_dir, 'scons.py'), sys.argv)
